# This GitHub Actions workflow is designed to execute Playwright tests across all supported browsers. 
# It supports manual triggers and utilizes a matrix strategy to run tests on 
# CHROME, FIREFOX, WEBKIT, CHROMIUM and EDGE browsers.

name: 03_All Supported Browsers

on:
  # Manual Trigger with all supported browsers
  workflow_dispatch:

jobs:

  # Job for running Playwright tests
  ui_tests_ALL_browsers:

    # Set a maximum timeout for the job
    timeout-minutes: 60

    # Define the machine on which tests will execute
    runs-on: ubuntu-latest

    # Use matrix strategy for parallel test execution on different browsers
    # strategy:
    #   matrix:
    #     browser: [CHROME, EDGE, WEBKIT, CHROMIUM, FIREFOX]

    steps:
      # Step 1: Checking out the code from the GitHub repository to the machine (ubuntu-latest)
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Installing Node.js
      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
      
      # Step 3: Install project dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Install Playwright browsers and dependencies
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      # Step 5: Run Playwright tests on all supported browsers from the matrix
      - name: Run Playwright UI tests
        # run: npm run tests:${{ matrix.browser }}:HEADLESS
        run: npm run tests:ALL:HEADLESS
        
        
      # Step 6: Upload Playwright test report as an artifact
      - name: Upload Reports
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: UI Tests Report
          path: playwright-report/
          retention-days: 30